[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Counterpart ranks, part 1/2
[[patches]]
[patches.pattern]
target = 'globals.lua'
pattern = "RENTAL = HEX('b18f43'),"
position = 'after'
match_indent = true
payload = '''COUNTERPART_RANKS = HEX('ef9ae7'),'''

# Counterpart ranks, part 2/2
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "legendary = G.C.RARITY[4],"
position = 'after'
match_indent = true
payload = '''counterpart_ranks = G.C.COUNTERPART_RANKS,'''