[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# The Patient, part 1/2
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = '''
for i=1, #cards_destroyed do
    G.E_MANAGER:add_event(Event({
        func = function()
            if SMODS.has_enhancement(cards_destroyed[i], 'm_glass') then
                cards_destroyed[i]:shatter()
            else
                cards_destroyed[i]:start_dissolve()
            end
            return true
        end
        }))
end
'''
position = 'after'
payload = '''
if G.GAME.blind and G.GAME.blind.name == 'The Patient' and not G.GAME.blind.disabled and G.GAME.current_round.hands_left > 0 and hand_chips*mult + G.GAME.chips >= G.GAME.blind.chips then
    SMODS.patient_gain_score(G.GAME.blind)
end
'''

# The Patient, part 2/2
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = "G.FUNCS.evaluate_round = function()"
position = 'after'
payload = '''
if G.GAME.patient_scoring then G.GAME.patient_scoring = nil end
'''