[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# The Patient
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = '''-- TARGET: effects after hand evaluation'''
position = 'after'
payload = '''
if G.GAME.blind and G.GAME.blind.name == 'The Patient' and not G.GAME.blind.disabled and G.GAME.current_round.hands_left > 0 then --and hand_chips*mult + G.GAME.chips >= G.GAME.blind.chips then
    SMODS.patient_gain_score(G.GAME.blind)
    G.GAME.blind.triggered = true
end
'''

# Alternate between black and white chess blinds, part 1/2
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_objects/blinds.lua"]'
match_indent = true
pattern = "if SMODS.optional_features.object_weights then"
position = 'before'
payload = '''
G.GAME.is_black_chess = math.random(0, 1) == 1
'''

# Alternate between black and white chess blinds, part 2/2
# Get new targets for Pawn, Rook, Knight and Princess, part 1/2
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = '''delay(0.4); SMODS.ante_end = true; ease_ante(1); SMODS.ante_end = nil; delay(0.4); check_for_unlock({type = 'ante_up', ante = G.GAME.round_resets.ante + 1})'''
position = 'before'
payload = '''
G.GAME.is_black_chess = not G.GAME.is_black_chess
Showdown.reset_chess_blinds_targets()
'''

# Get new targets for Pawn, Rook, Knight and Princess, part 2/2
[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = "self.deck:hard_set_T()"
position = 'after'
payload = '''
Showdown.reset_chess_blinds_targets()
'''

# Emerald Shard
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = "-- TARGET: main end_of_round evaluation"
position = 'after'
payload = '''
if G.GAME.emerald_shard_debuffed_cards then G.GAME.emerald_shard_debuffed_cards = nil end
'''