[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Add choices in booster with Vector
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = 'G.GAME.pack_choices = self.config.center.config.choose or 1'
position = "after"
match_indent = true
payload = '''
if G.GAME.showdown_vector and G.GAME.showdown_vector > 0 then
    self.ability.extra = self.ability.extra + 1
    G.GAME.showdown_vector = G.GAME.showdown_vector - 1
    G.GAME.pack_size = self.ability.extra
end
'''

# Hidden cards aren't required for cards unlocks
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
match_indent = true
pattern = "if #G.P_CENTER_POOLS.Tarot <= args.tarot_count then"
position = "at"
payload = '''
local tarotNb = #G.P_CENTER_POOLS.Tarot
for _, v in ipairs(G.P_CENTER_POOLS.Tarot) do
    if v.no_collection then tarotNb = tarotNb - 1 end
end
if tarotNb <= args.tarot_count then
'''

# Strange Thing replaces cards in pools
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
match_indent = true
pattern = "if v.no_pool_flag and G.GAME.pool_flags[v.no_pool_flag] then add = nil end"
position = "before"
payload = '''
if G.GAME.infection and G.GAME.infection.triggered > 0 and _type ~= 'Tag' then
    local pool_temp, cpt = {}, 1
    for _, v in ipairs(_pool) do
        table.insert(pool_temp, v)
    end
    while cpt <= G.GAME.infection.triggered or #pool_temp > 0 do
        local idx_temp = math.random(#pool_temp)
        local target, idx = pool_temp[idx_temp], -1
        for i, v in pairs(_pool) do
            if v == target then idx = i; break end
        end
        if idx ~= -1 then
            _pool[idx] = 'c_showdown_strange_thing'
            table.remove(pool_temp, idx_temp)
        end
        cpt = cpt + 1
    end
end

'''