[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Other decks don't have counterpart
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "if self.GAME.starting_params.no_faces and SMODS.Ranks[v.value].face then keep = false end"
position = 'after'
match_indent = true
payload = '''
if (SMODS.Ranks[v.value].counterpart and SMODS.Ranks[v.value].counterpart.is) or _r == 'showdown_Z' then
    keep = false
end
'''

# Calculus deck forces first booster in shop to be a Calculus booster, part 1/2
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "G.GAME.current_round.used_packs[i] = get_pack('shop_pack').key"
position = "at"
match_indent = true
payload = '''
G.GAME.current_round.used_packs[i] = get_pack('shop_pack', (G.GAME.first_booster_calculus and i == 1 and 'booster_calculus')).key
'''

# Calculus deck forces first booster in shop to be a Calculus booster, part 2/2
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = "if not G.GAME.first_shop_buffoon and not G.GAME.banned_keys['p_buffoon_normal_1'] then"
position = "at"
match_indent = true
payload = '''
if not G.GAME.first_booster_calculus and not G.GAME.first_shop_buffoon and not G.GAME.banned_keys['p_buffoon_normal_1'] then
'''

# Cheater deck card creation
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.current_round.hands_played = G.GAME.current_round.hands_played + 1"
position = "after"
match_indent = true
payload = '''
SMODS.calculate_context({post_hand = true})
'''

# Engineer deck, part 1/2
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local _pool, _pool_key = get_current_pool('Tag', nil, nil, append)"
position = "at"
match_indent = true
payload = '''
local _pool, _pool_key = get_current_pool(G.GAME.showdown_engineer and 'Switch' or 'Tag', nil, nil, append)
'''

# Engineer deck, part 2/2 (Versatile Joker too i guess) (Thanks Cardsauce)
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
_pool[#_pool + 1] = v.key
_pool_size = _pool_size + 1
'''
position = "at"
match_indent = true
payload = '''
if G.GAME.showdown_engineer and Showdown.tag_related_joker[v.key] then
    local weight = 4
    if G.GAME.selected_back.name == 'Engineer Deck' then
        local versatile = find_joker('versatile_joker')
        if #versatile > 0 then
            for i=1, #versatile do weight = math.floor(weight * versatile[i].ability.extra.tag_switch_mult) end
        end
    end
    -- can crash the game if weight is too high
    -- there's a configurable limit (100 by default) and a hardcoded limit (200)
    for i=1, math.min(weight, Showdown.config["Technical"]["Engineer Versatile Weight Limit"], 200) do
        _pool[#_pool + 1] = v.key -- no touchy
        _pool_size = _pool_size + 1 -- this is for not letting other mods mess with these 2 lines of code
    end
else
    _pool[#_pool + 1] = v.key
    _pool_size = _pool_size + 1
end
'''

# Random number of card in One of a Kind boosters
# One of a Kind Sleeve effect
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''for i = 1, _size do'''
position = 'before'
match_indent = true
payload = '''
if self.ability.min_cards ~= nil and self.ability.min_cards < _size and not G.GAME.showdown_one_of_a_kind_max_cards then
    _size = math.ceil(self.ability.min_cards + pseudorandom('one_of_a_kind_card_nb_'..G.SEED) * (_size - self.ability.min_cards))
    --_size = math.random(self.ability.min_cards, _size)
end
'''

# Versatile Joker (One of a Kind)
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = 'G.GAME.pack_choices = math.min((self.ability.choose or self.config.center.config.choose or 1) + (G.GAME.modifiers.booster_choice_mod or 0), self.ability.extra and math.max(1, self.ability.extra + (G.GAME.modifiers.booster_size_mod or 0)) or self.config.center.extra and math.max(1, self.config.center.extra + (G.GAME.modifiers.booster_size_mod or 0)) or 1)'
position = "after"
match_indent = true
payload = '''
if self.ability.min_cards ~= nil then
    G.GAME.pack_choices = G.GAME.pack_choices + (G.GAME.showdown_one_of_a_kind_more_selection ~= nil and G.GAME.showdown_one_of_a_kind_more_selection or 0)
end
'''