[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Ghost card destroying
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if SMODS.has_enhancement(scoring_hand[i], 'm_glass') and not scoring_hand[i].debuff and pseudorandom('glass') < G.GAME.probabilities.normal/(scoring_hand[i].ability.name == 'Glass Card' and scoring_hand[i].ability.extra or G.P_CENTERS.m_glass.config.extra) then"
position = "before"
match_indent = true
payload = '''
if scoring_hand[i].ability.name == 'm_showdown_ghost' and not scoring_hand[i].debuff and pseudorandom('ghost') < G.GAME.probabilities.normal/scoring_hand[i].ability.extra.shatter_chance then 
    destroyed = true
end
'''