[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Addition of removing_card context
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'if self.area then self.area:remove_card(self) end'
position = 'before'
match_indent = true
payload = '''
if G.jokers and G.jokers.cards then
    for i = 1, #G.jokers.cards do
        G.jokers.cards[i]:calculate_joker({removing_card = true, removed_card = self})
    end
end
'''

# Addition of post_removing context
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'if self.area then self.area:remove_card(self) end'
position = 'after'
match_indent = true
payload = '''
if G.jokers and G.jokers.cards then
    for i = 1, #G.jokers.cards do
        G.jokers.cards[i]:calculate_joker({post_removing = true, removed_card = self})
    end
end
'''

# Baby Jimbo
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = 'if self.cards[i] == card then'
position = 'after'
match_indent = true
payload = '''
G.GAME.latest_area_baby_jimbo = self
'''

# Check unlock for free item (one doller)
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = 'if c1.cost ~= 0 then'
position = 'before'
match_indent = true
payload = '''
check_for_unlock({type = 'buying_card', price = c1.cost})
'''

# Check unlock for sold card (egg drawing)
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'ease_dollars(self.sell_cost)'
position = 'before'
match_indent = true
payload = '''
check_for_unlock({type = 'selling_card', sell_cost = self.sell_cost})
'''

# Hands check for Chaos Card unlock
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.GAME.selected_back_key = selected_back"
position = "after"
match_indent = true
payload = '''
self.GAME.chaos_card_hands = {flush = false, straight = false, five = false}
'''

# Check unlock for buying card (what a steel)
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "playing_card_joker_effects({c1})"
position = "after"
match_indent = true
payload = '''
check_for_unlock({type = 'playing_card_added', card = c1})
'''

# Debuff first scored card (diplomatic immunity)
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "for i=1, #pures do"
position = "before"
match_indent = true
payload = '''
if next(find_joker('diplomatic_immunity')) and scoring_hand[1].debuff then
    scoring_hand[1]:set_debuff(false)
end
'''

# First scored card can't be destroyed (diplomatic immunity)
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = "local eval, post = eval_card(card, context)"
position = "before"
match_indent = true
payload = '''
if next(find_joker('diplomatic_immunity')) and (scoring_hand or context.cardarea.cards)[1] == card then
    destroyed = false
end
'''

# Reloading speeching abilities of Jean-Paul into a game
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = 'elseif self.config.center.name == "Square Joker" then'
position = "before"
match_indent = true
payload = '''
elseif self.config.center.name == "jean_paul" then
    giveSpeech(self)
'''

# Substitute Teacher, part 1/2
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.GAME.consumeable_usage_total = G.GAME.consumeable_usage_total or {tarot = 0, planet = 0, spectral = 0, tarot_planet = 0, all = 0}"
position = "at"
match_indent = true
payload = '''
G.GAME.consumeable_usage_total = G.GAME.consumeable_usage_total or {tarot = 0, planet = 0, spectral = 0, tarot_planet = 0, mathematic = 0, all = 0}
'''

# Substitute Teacher, part 2/2
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "elseif card.config.center.set == 'Spectral' then  G.GAME.consumeable_usage_total.spectral = G.GAME.consumeable_usage_total.spectral + 1"
position = "after"
match_indent = true
payload = '''
elseif card.config.center.set == 'Mathematic' then G.GAME.consumeable_usage_total.mathematic = G.GAME.consumeable_usage_total.mathematic + 1
'''

# Substitute Teacher unlock, part 1/2
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "c_tarots_bought = 0,"
position = "after"
match_indent = true
payload = '''
c_maths_used = 0,
'''

# Substitute Teacher unlock, part 2/2
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "elseif not nc then draw_card(G.hand, G.play, 1, 'up', true, card, nil, mute) end"
position = "after"
match_indent = true
payload = '''
if card.config.center.set == 'Mathematic' then
    inc_career_stat('c_maths_used', 1)
end
'''

# Bugged Seed unlock
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "check_for_unlock({type = 'win_challenge'})"
position = "before"
match_indent = true
payload = '''
if G.GAME.challenge == 'c_showdown_7LB2WVPK' then
    check_for_unlock({type = '7LB2WVPK'})
end
'''

# Red Coins, part 1/4
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
match_indent = true
pattern = "if G.GAME.current_round.discards_left > 0 and G.GAME.modifiers.money_per_discard then"
position = "at"
payload = '''
if (G.GAME.current_round.discards_left > 0 and G.GAME.modifiers.money_per_discard) or #find_joker('red_coins') > 0 then
    local bonusDiscard = 0
    if #find_joker('red_coins') > 0 then
        for i=1, #find_joker('red_coins') do
            bonusDiscard = bonusDiscard + find_joker('red_coins')[i].ability.extra.money
        end
        bonusDiscard = bonusDiscard * G.GAME.current_round.discards_left
    end
'''

# Red Coins, part 2/4
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
match_indent = true
pattern = "add_round_eval_row({dollars = G.GAME.current_round.discards_left*(G.GAME.modifiers.money_per_discard), disp = G.GAME.current_round.discards_left, bonus = true, name='discards', pitch = pitch})"
position = "at"
payload = '''
local totalMoney = G.GAME.current_round.discards_left * (G.GAME.modifiers.money_per_discard or 0) + bonusDiscard
if totalMoney > 0 then add_round_eval_row({dollars = totalMoney, disp = G.GAME.current_round.discards_left, bonus = true, name='discards', pitch = pitch}) end
'''

# Red Coins, part 3/4
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
match_indent = true
pattern = "dollars = dollars +  G.GAME.current_round.discards_left*(G.GAME.modifiers.money_per_discard)"
position = "at"
payload = '''
dollars = dollars + totalMoney
'''

# Red Coins, part 4/4
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
match_indent = true
pattern = "table.insert(left_text, {n=G.UIT.O, config={object = DynaText({string = {\" \"..localize{type = 'variable', key = 'remaining_discard_money', vars = {G.GAME.modifiers.money_per_discard or 0}}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})"
position = "at"
payload = '''
local bonusDiscard = 0
if #find_joker('red_coins') > 0 then
    for i=1, #find_joker('red_coins') do
        bonusDiscard = bonusDiscard + find_joker('red_coins')[i].ability.extra.money
    end
end
table.insert(left_text, {n=G.UIT.O, config={object = DynaText({string = {" "..localize{type = 'variable', key = 'remaining_discard_money', vars = {(G.GAME.modifiers.money_per_discard or 0)+bonusDiscard}}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})
'''

# Money Cutter, part 1/5
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
match_indent = true
pattern = "dollars = dollars + G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)"
position = "before"
payload = '''
check_for_unlock({type = 'interest', money = G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)})
'''

# Money Cutter, part 2/5
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
match_indent = true
pattern = "if G.GAME.current_round.hands_left > 0 and not G.GAME.modifiers.no_extra_hand_money then"
position = "at"
payload = '''
if (G.GAME.current_round.hands_left > 0 and not G.GAME.modifiers.no_extra_hand_money) or #find_joker('money_cutter') > 0 then
    local bonusHand = 0
    if #find_joker('money_cutter') > 0 then
        for i=1, #find_joker('money_cutter') do
            bonusHand = bonusHand + find_joker('money_cutter')[i].ability.extra.money
        end
        bonusHand = bonusHand * G.GAME.current_round.hands_left
    end
'''

# Money Cutter, part 3/5 (Burning Switch btw)
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
match_indent = true
pattern = "add_round_eval_row({dollars = G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1), disp = G.GAME.current_round.hands_left, bonus = true, name='hands', pitch = pitch})"
position = "at"
payload = '''
local totalMoney = (G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1) + bonusHand) * (G.GAME.burning_double_hands and 2 or 1)
add_round_eval_row({dollars = totalMoney, disp = G.GAME.current_round.hands_left, bonus = true, name='hands', pitch = pitch})
G.GAME.burning_double_hands = false
'''

# Money Cutter, part 4/5
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
match_indent = true
pattern = "dollars = dollars + G.GAME.current_round.hands_left*(G.GAME.modifiers.money_per_hand or 1)"
position = "at"
payload = '''
dollars = dollars + totalMoney
'''

# Money Cutter, part 5/5
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
match_indent = true
pattern = "table.insert(left_text, {n=G.UIT.O, config={object = DynaText({string = {\" \"..localize{type = 'variable', key = 'remaining_hand_money', vars = {G.GAME.modifiers.money_per_hand or 1}}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})"
position = "at"
payload = '''
local bonusHand = 0
if #find_joker('money_cutter') > 0 then
    for i=1, #find_joker('money_cutter') do
        bonusHand = bonusHand + find_joker('money_cutter')[i].ability.extra.money
    end
end
table.insert(left_text, {n=G.UIT.O, config={object = DynaText({string = {" "..localize{type = 'variable', key = 'remaining_hand_money', vars = {(G.GAME.modifiers.money_per_hand or 1)+bonusHand}}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})
'''

# Versatile Joker (Yellow Deck)
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
match_indent = true
pattern = "ease_dollars(G.GAME.current_round.dollars)"
position = "after"
payload = '''
for i = 1, #G.jokers.cards do
    G.jokers.cards[i]:calculate_joker({cash_out = true, money = G.GAME.current_round.dollars, interest = G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)})
end
'''

# Versatile Joker (Plasma Deck), part 1/2
[[patches]]
[patches.pattern]
target = "back.lua"
match_indent = true
pattern = "local tot = args.chips + args.mult"
position = "before"
payload = '''
if (next(find_joker('versatile_joker')) or next(find_joker('versatile_joker_all_in_one'))) and G.GAME.selected_back.name == 'Plasma Deck' then
    local tot = args.chips + args.mult
    args.chips = args.chips + math.floor(tot/4)
    args.mult = args.mult + math.floor(tot/4)
else
'''

# Versatile Joker (Plasma Deck), part 2/2
[[patches]]
[patches.pattern]
target = "back.lua"
match_indent = true
pattern = "update_hand_text({delay = 0}, {mult = args.mult, chips = args.chips})"
position = "before"
payload = '''
end
'''

# Versatile Joker (Starter Deck)
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
match_indent = true
pattern = "inc_career_stat('c_wins', 1)"
position = "after"
payload = '''
if G.GAME.selected_back.name == 'Starter Deck' and (next(find_joker('versatile_joker')) or next(find_joker('versatile_joker_all_in_one'))) then
    G.PROFILES[G.SETTINGS.profile].starter_next_run = true
end
'''

# Versatile Joker (Magic Deck)
[[patches]]
[patches.regex]
target = "card.lua"
#match_indent = true
#line_prepend = '$indent'
pattern = "(?<indent1>[\t ]*)local card = create_card[(]'Tarot_Planet', G.consumeables, nil, nil, nil, nil, G.GAME.last_tarot_planet, 'fool'[)][\n](?<indent2>[\t ]*)card:add_to_deck[(][)][\n](?<indent3>[\t ]*)G.consumeables:emplace[(]card[)]"
position = "after"
payload = '''

                for i = 1, #G.jokers.cards do
                    G.jokers.cards[i]:calculate_joker({using_fool = true, created_card = card})
                end
'''

# banana unlock
[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = "if pseudorandom(self.ability.name == 'Cavendish' and 'cavendish' or 'gros_michel') < G.GAME.probabilities.normal/self.ability.extra.odds then"
position = "after"
payload = '''
check_for_unlock({type = 'extinct', name = self.ability.name})
'''

# Versatile Joker (Nebula Deck), part 1/2
[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = "update_hand_text({sound = 'button', volume = 0.7, pitch = 0.8, delay = 0.3}, {handname=localize(self.ability.consumeable.hand_type, 'poker_hands'),chips = G.GAME.hands[self.ability.consumeable.hand_type].chips, mult = G.GAME.hands[self.ability.consumeable.hand_type].mult, level=G.GAME.hands[self.ability.consumeable.hand_type].level})"
position = "before"
payload = '''
local versatile, amount = find_joker('versatile_joker'), 1
if #versatile > 0 and G.GAME.selected_back.name == 'Nebula Deck' then
    for i=1, #versatile do amount = amount + versatile[i].ability.extra.planet end
end
versatile = find_joker('versatile_joker_all_in_one')
if #versatile > 0 and G.GAME.selected_back.name == 'Nebula Deck' then
    for i=1, #versatile do amount = amount + versatile[i].ability.extra.planet end
end
amount = math.floor(amount)
'''

# Versatile Joker (Nebula Deck), part 2/2
[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = "level_up_hand(used_tarot, self.ability.consumeable.hand_type)"
position = "at"
payload = '''
level_up_hand(used_tarot, self.ability.consumeable.hand_type, nil, amount)
'''

# The Idol doesn't pick counterparts
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
match_indent = true
pattern = "valid_idol_cards[#valid_idol_cards+1] = v"
position = "at"
payload = '''
if v.base.id > 0 then
    valid_idol_cards[#valid_idol_cards+1] = v
end
'''

# Mail in Rebate doesn't pick counterparts
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
match_indent = true
pattern = "valid_mail_cards[#valid_mail_cards+1] = v"
position = "at"
payload = '''
if v.base.id > 0 then
    valid_mail_cards[#valid_mail_cards+1] = v
end
'''

# Versatile Joker (Ghost Deck)
[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = "if (self.ability.set == 'Planet' or (self.ability.set == 'Booster' and self.ability.name:find('Celestial'))) and #find_joker('Astronomer') > 0 then self.cost = 0 end"
position = "after"
payload = '''
if (self.ability.set == 'Spectral' or (self.ability.set == 'Booster' and self.ability.name:find('Spectral'))) and (#find_joker('versatile_joker') > 0 or #find_joker('versatile_joker_all_in_one') > 0) and G.GAME.selected_back.name == 'Ghost Deck' then self.cost = 0 end
'''

# Joker on Joker stickers effects
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
match_indent = true
pattern = '''-- Calculate context.other_joker effects'''
position = "before"
payload = '''
-- Joker on Joker stickers effects
if _card.ability.set == 'Joker' or _card.ability.set == 'Default' or _card.ability.set == 'Enhanced' then
    for _, _area in ipairs(SMODS.get_card_areas('jokers')) do
        for _, _joker in ipairs(_area.cards) do
            for k, w in pairs(_card.ability) do
                -- TARGET: add context.other_something identifier to your cards
                local joker_sticker_eval,post = eval_card(_joker, {full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, other_card = _card, ability = {key=k, value=w} })
                if next(joker_sticker_eval) then
                    if joker_sticker_eval.edition then joker_sticker_eval.edition = {} end
                    joker_sticker_eval.jokers.juice_card = _joker
                    table.insert(effects, joker_sticker_eval)
                    for _, v in ipairs(post) do effects[#effects+1] = v end
                    if joker_sticker_eval.retriggers then
                        for rt = 1, #joker_sticker_eval.retriggers do
                            local rt_eval, rt_post = eval_card(_card, {full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, other_card = _card, ability = {key=k, value=w}, retrigger_joker = true})
                            table.insert(effects, {joker_sticker_eval.retriggers[rt]})
                            table.insert(effects, rt_eval)
                            for _, v in ipairs(rt_post) do effects[#effects+1] = v end
                        end
                    end
                end
            end
        end
    end
end

'''

# Label unlock
[[patches]]
[patches.pattern]
target = 'tag.lua'
match_indent = true
pattern = '''function Tag:yep(message, _colour, func)'''
position = 'after'
payload = '''
G.GAME.tag_used = (G.GAME.tag_used or 0) + 1
check_for_unlock({type = 'tag_used', tag = self})
'''

# Whatever last played hand
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = '''set_hand_usage(text)'''
position = 'after'
payload = '''
G.GAME.last_played_hand = text
'''

# Pop-Up
[[patches]]
[patches.pattern]
target = 'tag.lua'
match_indent = true
pattern = '''function Tag:yep(message, _colour, func)'''
position = 'after'
payload = '''
for i=1, #find_joker('pop_up') do
    G.GAME.consumeable_buffer = G.GAME.consumeable_buffer + 1
    G.E_MANAGER:add_event(Event({
        trigger = 'after',
        delay = 0.0,
        func = function()
            if G.consumeables.config.card_limit > #G.consumeables.cards then
                local _card = SMODS.create_card({set = 'Tarot_Planet', area = G.consumeables})
                _card:add_to_deck()
                G.consumeables:emplace(_card)
            end
            G.GAME.consumeable_buffer = G.GAME.consumeable_buffer - 1
            return true
        end
    }))
end
'''

# debuffed_card context
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = 'if extra and extra.playing_cards_created then'
position = 'before'
match_indent = true
payload = '''
if eval_type == 'debuff' then
    for _, v in ipairs(G.jokers.cards) do
        v:calculate_joker({debuffed_card = card})
    end
end
'''

# Versatile Joker (Engineer Deck)
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = 'elseif not (G.GAME.used_jokers[v.key] and not pool_opts.allow_duplicates and not next(find_joker("Showman"))) and'
position = 'at'
match_indent = true
payload = '''
elseif (not (G.GAME.used_jokers[v.key] and not pool_opts.allow_duplicates and not next(find_joker("Showman")))) or
    (((next(find_joker("versatile_joker")) and G.GAME.selected_back.name == 'Engineer Deck') or next(find_joker("versatile_joker_all_in_one"))) and Showdown.tag_related_joker[v.key]) and
'''

# Jimbocoin unlock, part 1/2
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''check_for_unlock({type = 'money'})'''
position = 'after'
match_indent = true
payload = '''
if not G.shop then
    G.GAME.money_gain_in_round = (G.GAME.money_gain_in_round or 0) + mod -- maybe change if can only accept positive increments
    check_for_unlock({type = 'money_gain_in_round', money_gain = G.GAME.money_gain_in_round})
end
'''

# Jimbocoin unlock, part 2/2
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''ease_dollars(G.GAME.current_round.dollars)'''
position = 'after'
match_indent = true
payload = '''
G.GAME.money_gain_in_round = 0
'''