[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# For testing
[[patches]]
[patches.pattern]
target = "controller.lua"
pattern = "if not _RELEASE_MODE then"
position = "at"
match_indent = true
payload = '''
if _RELEASE_MODE then
'''

# Counterpart ranks and mathematic color, part 1/2
[[patches]]
[patches.pattern]
target = 'globals.lua'
pattern = "RENTAL = HEX('b18f43'),"
position = 'after'
match_indent = true
payload = '''
COUNTERPART_RANKS = HEX('485fab'),
SHOWDOWN_CALCULUS = HEX('b84242'),
SHOWDOWN_CALCULUS_DARK = HEX('8a3434'),
'''

# Counterpart ranks and mathematic color, part 2/2
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "legendary = G.C.RARITY[4],"
position = 'after'
match_indent = true
payload = '''
counterpart_ranks = G.C.COUNTERPART_RANKS,
showdown_calculus = G.C.SHOWDOWN_CALCULUS,
showdown_calculus_dark = G.C.SHOWDOWN_CALCULUS_DARK,
'''

# Init Showdown global through lovely
[[patches]]
[patches.pattern]
target = "main.lua"
match_indent = true
pattern = '''function love.load()'''
position = "before"
payload = '''
Showdown = {}
Showdown.extraSuits = {}
Showdown.versatile = {}
Showdown.casino = {}
'''

# xChips eval state
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
match_indent = true
pattern = '''elseif eval_type == 'h_mult' then'''
position = "before"
payload = '''
elseif eval_type == 'xchips' then 
    --sound = 'xchips'
    sound = 'foil2'
    volume = 0.7
    amt = amt
    text = localize{type='variable',key='a_xchips',vars={amt}}
    colour = G.C.CHIPS
    config.type = 'fade'
    config.scale = 0.7
'''

# Casino stickers apply
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if card.ability.consumeable and not skip_materialize then card:start_materialize() end"
position = "after"
match_indent = true
payload = '''
if card.ability.set == 'Joker' and G.GAME.casino_rate and pseudorandom('casino') < G.GAME.casino_rate then
    pseudorandom_element(Showdown.casino, pseudoseed('casino')):apply(card, true)
end
'''

# Mushroom sticker works for drawn cards
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if card then drawn = true end"
position = "after"
match_indent = true
payload = '''
if card.ability.showdown_mushroom then
    G.E_MANAGER:add_event(Event({func = function()
        G.hand:change_size(1)
        G.GAME.round_resets.temp_handsize = (G.GAME.round_resets.temp_handsize or 0) + 1
    return true end }))
end
'''