[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# For testing
[[patches]]
[patches.pattern]
target = "controller.lua"
pattern = "if not _RELEASE_MODE then"
position = "at"
match_indent = true
payload = '''
if _RELEASE_MODE then
'''

# Text colors, part 1/2
[[patches]]
[patches.pattern]
target = 'globals.lua'
pattern = "RENTAL = HEX('b18f43'),"
position = 'after'
match_indent = true
payload = '''
COUNTERPART_RANKS = HEX('485fab'),
SHOWDOWN_CALCULUS = HEX('b84242'),
SHOWDOWN_CALCULUS_DARK = HEX('8a3434'),
SWITCH = HEX('acc3f0'),
SHOWDOWN_LOGIC = HEX('808080'),
SHOWDOWN_LOGIC_DARK = HEX('595959'),
'''

# Text colors, part 2/2
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "legendary = G.C.RARITY[4],"
position = 'after'
match_indent = true
payload = '''
counterpart_ranks = G.C.COUNTERPART_RANKS,
showdown_calculus = G.C.SHOWDOWN_CALCULUS,
showdown_calculus_dark = G.C.SHOWDOWN_CALCULUS_DARK,
showdown_logic = G.C.SHOWDOWN_LOGIC,
showdown_logic_dark = G.C.SHOWDOWN_LOGIC_DARK,
'''

# Init Showdown global through lovely
[[patches]]
[patches.pattern]
target = "main.lua"
match_indent = true
pattern = '''function love.load()'''
position = "before"
payload = '''
Showdown = {}
Showdown.extraSuits = {}
Showdown.versatile = {}
Showdown.casino = {}
Showdown.tag_related_joker = {}
'''

# Text color on toggle buttons
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
match_indent = true
pattern = '''{n=G.UIT.T, config={text = args.label, scale = args.label_scale, colour = G.C.UI.TEXT_LIGHT}},'''
position = "at"
payload = '''
{n=G.UIT.T, config={text = args.label, scale = args.label_scale, colour = args.label_color or G.C.UI.TEXT_LIGHT}},
'''

# Show required decks for the Versatility achievement, part 1/2
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/ui.lua"]'''
match_indent = true
pattern = '''temp_achievement.hovering = true'''
position = "after"
payload = '''
if v.key == 'ach_showdown_versatility' then
    Showdown.versatility_description(temp_achievement)
end
'''

# Show required decks for the Versatility achievement, part 2/2
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/ui.lua"]'''
match_indent = true
pattern = '''temp_achievement.stop_hover = function() temp_achievement.hovering = false; Node.stop_hover(temp_achievement); temp_achievement.hover_tilt = 0 end'''
position = "at"
payload = '''
temp_achievement.stop_hover = function()
    temp_achievement.hovering = false
    if temp_achievement.children.speech_bubble then
        temp_achievement.children.speech_bubble:remove()
        temp_achievement.children.speech_bubble = nil
    end
    Node.stop_hover(temp_achievement)
    temp_achievement.hover_tilt = 0
end
'''