[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Money Switch, part 1/2
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
match_indent = true
pattern = '''local blind_sprite = Sprite(0, 0, 0.7,0.7, G.ASSET_ATLAS['tags'], copy_table(config.pos))'''
position = 'at'
payload = '''
local blind_sprite = Sprite(0, 0, 0.7,0.7, G.ASSET_ATLAS[config.atlas or 'tags'], copy_table(config.pos))
'''

# Money Switch, part 2/2
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = '''add_round_eval_row({dollars = ret.dollars, bonus = true, name='tag'..i, pitch = pitch, condition = ret.condition, pos = ret.pos, tag = ret.tag})'''
position = 'at'
payload = '''
add_round_eval_row({dollars = ret.dollars, bonus = true, name='tag'..i, pitch = pitch, condition = ret.condition, pos = ret.pos, atlas = ret.atlas, tag = ret.tag})
'''

# Burning Switch
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = '''add_round_eval_row({dollars = G.GAME.blind.dollars, name='blind1', pitch = pitch})'''
position = 'before'
payload = '''
if G.GAME.burning_double_hands then G.GAME.blind.dollars = 0 end
'''